home:
    path: /
    defaults: { _controller: AppBundle:Home/Index:index }


register:
    path: /register
    defaults: { _controller: AppBundle:Register/Register:index }

liste:
    path:     /liste/{type}
    defaults: { _controller: AppBundle:Liste/Liste:index }

listeHot:
    path:     /liste/{type}
    defaults: { _controller: AppBundle:Liste/Liste:index }